/*
*	New C++ Header  File starts here.
*	This file should be named NMLmsgExn_n_codegen_protos.hh
*	Automatically generated by NML CodeGen Java Applet.
*	with command line arguments :  HHFile=NMLmsgExn.hh HHFile=NMLmsgExn.cc
*
*	.gen script :
*		0:load NMLmsgExn.hh
*		1:clear
*		2:select_from_file NMLmsgExn.hh
*		3:generate C++ protos>NMLmsgExn_n_codegen_protos.hh
*		4:generate C++ format>NMLmsgExn_n.cc
*		5:generate C++ update>NMLmsgExn_n.cc
*		6:generate C++ constructor>NMLmsgExn_n.cc
*		7:exit
*
*/

#ifndef NMLmsgExn_n_codegen_protos_hh_included
#define NMLmsgExn_n_codegen_protos_hh_included

// Include all NML, CMS, and RCS classes and functions
#include "rcs.hh"

// Include command and status message definitions
#include "NMLmsgExn.hh"
#include "CommonDefinitionX.hh"

// Forward Function Prototypes
extern void nmlupdate(CMS *cms, LOCAL_POS_DATA *x);
extern void initialize_LOCAL_POS_DATA(LOCAL_POS_DATA *x);
extern void nmlupdate(CMS *cms, LOCAL_COORDINATE *x);
extern void initialize_LOCAL_COORDINATE(LOCAL_COORDINATE *x);
extern void nmlupdate(CMS *cms, PositionData *x);
extern void initialize_PositionData(PositionData *x);


#ifndef MAX_NMLMSGEXNAME_LENGTH
#define MAX_NMLMSGEXNAME_LENGTH 9
#endif
#ifndef NMLMSGEXNAME_LIST_LENGTH
#define NMLMSGEXNAME_LIST_LENGTH 2
#endif


/* This list must be in alphabetical order and the three lists must correspond. */
extern const NMLTYPE NMLmsgExid_list[NMLMSGEXNAME_LIST_LENGTH];
extern const size_t NMLmsgExsize_list[NMLMSGEXNAME_LIST_LENGTH];

// Enumerated Type Constants

extern int NMLmsgExFormat(NMLTYPE type, void *buffer, CMS *cms);

#endif
	/* # endif NMLmsgExn_n_codegen_protos_hh_included */ 

