#ifndef XS_ERROR_CODE_H_
#define XS_ERROR_CODE_H_

#define XS_OK (0x0)

#define PARAM_BASE_ERROR (0x1000)
#define PARAM_STATIONS_COUNT_ERROR PARAM_BASE_ERROR + (0x01)
#define PARAM_MAP_ENV_ERROR PARAM_BASE_ERROR + (0x02)

#define IO_BASE_ERROR (0x2000)
#define IO_TOTALMAP_LOAD_ERROR IO_BASE_ERROR + (0x01)
#define IO_SHPFILE_LOAD_ERROR IO_BASE_ERROR + (0x02)
#define IO_RANGE_LOAD_ERROR IO_BASE_ERROR + (0x03)
#define IO_MAP_TITLE_LOAD_ERROR IO_BASE_ERROR + (0x04)
#define IO_MAPPOSITION_FILE_LOAD_ERROR IO_BASE_ERROR + (0x05)

#define RCS_BASE_ERROR (0x3000)
#define RCS_LOCALIZE_ERROR RCS_BASE_ERROR + (0x01)
#define RCS_LOAD_LIDAR_ERROR RCS_BASE_ERROR + (0x02)
#define RCS_GPS_ERROR RCS_BASE_ERROR + (0x03)
#define RCS_LOCALPOSE_ERROR RCS_BASE_ERROR + (0x04)

#define MAP_BASE_ERROR (0x4000)
#define MAP_WORLD2MAP_ERROR MAP_BASE_ERROR + (0x01)
#define MAP_POSEIN_OUT_OF_MAPRANGE MAP_BASE_ERROR + (0x02)

#define MATCH_BASE_ERROR (0x5000)
#define MATCH_ERROR MATCH_BASE_ERROR + (0x01)
#define STATUS_BUSY_ERROR MATCH_BASE_ERROR + (0x02)

#define TIME_OUT_ERROR (0x6000)

#define MATCH_STATUS_ERROR (0x7000)
#define MOVE_VEHICLE_ERROR MATCH_STATUS_ERROR + (0x01)
#define RECOVER_BY_ITSELF MATCH_STATUS_ERROR + (0x02)
#define BREAK_BY_MANUAL MATCH_STATUS_ERROR + (0x03)

#endif
